# Import relevant libraries

In [1]:
import os
import pandas as pd
import numpy as np

# Load Data & Merge

In [2]:
# set file path
base_path = '../..'
file_path_1 = os.path.join(base_path, 'datasets',
                           'tech_roundabout_coordinates.csv')

# load data
tech_roundabout_full = pd.read_csv(file_path_1)

In [3]:
# set file path
file_path_2 = os.path.join(base_path, 'datasets', 'features_data.csv')

# load data
features = pd.read_csv(file_path_2)

In [4]:
# merge both data
all_data = pd.merge(tech_roundabout_full,
                    features,
                    on='CompanyName',
                    how='inner')

# Split Incorporation Date to find Sector Codes and Values

In [5]:
# sort value by date
all_data = all_data.sort_values('IncorporationDate', ascending=True)

In [6]:
# remove all companies before 1990
all_data = all_data[all_data['year'] > 1990]

In [7]:
# split sector code so we can identify sector values

x = all_data['SICCode.SicText_1'].str.rsplit(pat='-', expand=True)

y = all_data['SICCode.SicText_2'].str.rsplit(pat='-', expand=True)

z = all_data['SICCode.SicText_3'].str.rsplit(pat='-', expand=True)

q = all_data['SICCode.SicText_4'].str.rsplit(pat='-', expand=True)

all_data['sector_code_1'] = x[0]
all_data['sector_name_1'] = x[1]
all_data['sector_code_2'] = y[0]
all_data['sector_name_2'] = y[1]
all_data['sector_code_3'] = z[0]
all_data['sector_name_3'] = z[1]
all_data['sector_code_4'] = q[0]
all_data['sector_name_4'] = q[1]

In [8]:
all_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 94975 entries, 16318 to 22167
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CompanyName          94975 non-null  object
 1   RegAddress.PostCode  94975 non-null  object
 2   RegAddress.PostTown  94975 non-null  object
 3   latitude             93910 non-null  float64
 4   longitude            93910 non-null  float64
 5   CompanyNumber        94975 non-null  object
 6   CompanyCategory      94975 non-null  object
 7   CompanyStatus        94975 non-null  object
 8   DissolutionDate      0 non-null      float64
 9   IncorporationDate    94975 non-null  object
 10  SICCode.SicText_1    94975 non-null  object
 11  SICCode.SicText_2    19042 non-null  object
 12  SICCode.SicText_3    9941 non-null   object
 13  SICCode.SicText_4    5502 non-null   object
 14  year                 94975 non-null  int64
 15  month                94975 non-null  int64
 16  sector_code_1        94975 non-null  object
 17  sector_name_1        91659 non-null  object
 18  sector_code_2        19042 non-null  object
 19  sector_name_2        19042 non-null  object
 20  sector_code_3        9941 non-null   object
 21  sector_name_3        9941 non-null   object
 22  sector_code_4        5502 non-null   object
 23  sector_name_4        5502 non-null   object
dtypes: float64(3), int64(2), object(19)
memory usage: 18.1+ MB

# Clean Data and remove unnecessary columns

In [9]:
# remove spaces in columns
col_names = [col_name.strip() for col_name in all_data.columns]

# set column names
all_data.columns = col_names

In [10]:
# remove columns
columns_to_remove = [
    'RegAddress.PostCode', 'RegAddress.PostTown', 'SICCode.SicText_1',
    'SICCode.SicText_2', 'SICCode.SicText_3', 'SICCode.SicText_4'
]

cleaned_data = all_data.drop(columns_to_remove, axis=1)

In [11]:
cleaned_data.loc[cleaned_data['CompanyStatus'] != 'Active']

,CompanyName,latitude,longitude,CompanyNumber,CompanyCategory,CompanyStatus,DissolutionDate,IncorporationDate,year,month,sector_code_1,sector_name_1,sector_code_2,sector_name_2,sector_code_3,sector_name_3,sector_code_4,sector_name_4
81846,STAVERTON LIMITED,NaN,NaN,02634159,Private Limited Company,ADMINISTRATIVE RECEIVER,NaN,1991-01-08,1991,1,3612,Manufacture other office & shop furniture,NaN,NaN,NaN,NaN,NaN,NaN
62060,NORBUT LTD,51.523267,-0.098041,02573874,Private Limited Company,Liquidation,NaN,1991-01-15,1991,1,65120,Non,NaN,NaN,NaN,NaN,NaN,NaN
25997,E.J.W. LIMITED,51.523267,-0.098041,02576196,Private Limited Company,Liquidation,NaN,1991-01-23,1991,1,68100,Buying and selling of own real estate,70229,Management consultancy activities other than ...,NaN,NaN,NaN,NaN
43425,INSTINCTIVE PARTNERS LIMITED,51.515626,-0.093661,02578528,Private Limited Company,Active - Proposal to Strike off,NaN,1991-01-31,1991,1,70210,Public relations and communications activities,NaN,NaN,NaN,NaN,NaN,NaN
86801,THE OMEGA GROUP (UK) LIMITED,51.524565,-0.112042,02596788,Private Limited Company,Liquidation,NaN,1991-02-04,1991,2,3663,Other manufacturing,5190,Other wholesale,7415,Holding Companies including Head Offices,9305,Other service activities n.e.c.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32230,FLOATH LIMITED,51.524845,-0.092670,12596039,Private Limited Company,Active - Proposal to Strike off,NaN,2020-12-05,2020,12,62012,Business and domestic software development,NaN,NaN,NaN,NaN,NaN,NaN
13699,BROOKLANE COLLEGE LIMITED,51.527246,-0.088808,12596774,Private Limited Company,Active - Proposal to Strike off,NaN,2020-12-05,2020,12,78200,Temporary employment agency activities,NaN,NaN,NaN,NaN,NaN,NaN
8162,AUTOMOTIVE RECRUITMENT AGENCY LTD,51.527246,-0.088808,12597204,Private Limited Company,Active - Proposal to Strike off,NaN,2020-12-05,2020,12,78200,Temporary employment agency activities,NaN,NaN,NaN,NaN,NaN,NaN
17993,CITY WORKS HULL LTD,51.527246,-0.088808,12597373,Private Limited Company,Active - Proposal to Strike off,NaN,2020-12-05,2020,12,78200,Temporary employment agency activities,NaN,NaN,NaN,NaN,NaN,NaN
73944,RIVVIT MEDIA LTD,51.527246,-0.088808,12667575,Private Limited Company,Active - Proposal to Strike off,NaN,2020-12-06,2020,12,96090,Other service activities n.e.c.,NaN,NaN,NaN,NaN,NaN,NaN

# Create dictionary that shows count of each sector code

In [12]:
# find unqiue sector values
unique_codes = np.unique(cleaned_data['sector_code_1'], return_counts=True)

In [13]:
# create dictionary with count of each sector values

d = {}
for idx, val in enumerate(unique_codes[0]):
    d[val] = unique_codes[1][idx]

In [14]:
sorted(d.items(), key=lambda item: item[1])

[('01150 ', 1),
 ('01210 ', 1),
 ('01220 ', 1),
 ('01230 ', 1),
 ('01270 ', 1),
 ('01440 ', 1),
 ('01470 ', 1),
 ('05101 ', 1),
 ('08110 ', 1),
 ('08120 ', 1),
 ('10310 ', 1),
 ('13939 ', 1),
 ('14141 ', 1),
 ('14310 ', 1),
 ('14390 ', 1),
 ('15110 ', 1),
 ('16210 ', 1),
 ('17110 ', 1),
 ('17120 ', 1),
 ('1823 ', 1),
 ('20200 ', 1),
 ('20600 ', 1),
 ('2125 ', 1),
 ('2211 ', 1),
 ('2225 ', 1),
 ('23110 ', 1),
 ('23140 ', 1),
 ('23320 ', 1),
 ('23430 ', 1),
 ('23490 ', 1),
 ('23630 ', 1),
 ('23690 ', 1),
 ('24420 ', 1),
 ('24510 ', 1),
 ('24520 ', 1),
 ('25210 ', 1),
 ('25300 ', 1),
 ('25500 ', 1),
 ('25910 ', 1),
 ('25930 ', 1),
 ('25940 ', 1),
 ('2621 ', 1),
 ('26301 ', 1),
 ('2812 ', 1),
 ('28210 ', 1),
 ('28240 ', 1),
 ('28410 ', 1),
 ('2851 ', 1),
 ('29203 ', 1),
 ('2922 ', 1),
 ('2924 ', 1),
 ('2956 ', 1),
 ('30910 ', 1),
 ('3162 ', 1),
 ('32110 ', 1),
 ('3511 ', 1),
 ('3612 ', 1),
 ('38120 ', 1),
 ('4030 ', 1),
 ('4512 ', 1),
 ('4523 ', 1),
 ('4533 ', 1),
 ('4541 ', 1),
 ('4544 ', 1),
 ('4550 ', 1),
 ('46491 ', 1),
 ('46640 ', 1),
 ('5030 ', 1),
 ('50300 ', 1),
 ('5114 ', 1),
 ('5132 ', 1),
 ('5134 ', 1),
 ('5138 ', 1),
 ('5153 ', 1),
 ('5156 ', 1),
 ('5164 ', 1),
 ('5186 ', 1),
 ('5242 ', 1),
 ('5274 ', 1),
 ('6022 ', 1),
 ('6023 ', 1),
 ('6311 ', 1),
 ('6322 ', 1),
 ('6330 ', 1),
 ('65201 ', 1),
 ('6601 ', 1),
 ('6603 ', 1),
 ('6713 ', 1),
 ('7012 ', 1),
 ('7031 ', 1),
 ('7032 ', 1),
 ('7134 ', 1),
 ('7210 ', 1),
 ('7230 ', 1),
 ('7240 ', 1),
 ('7413 ', 1),
 ('7470 ', 1),
 ('8042 ', 1),
 ('8512 ', 1),
 ('8531 ', 1),
 ('8532 ', 1),
 ('9112 ', 1),
 ('01190 ', 2),
 ('01240 ', 2),
 ('01410 ', 2),
 ('01621 ', 2),
 ('02300 ', 2),
 ('07210 ', 2),
 ('10200 ', 2),
 ('10512 ', 2),
 ('10730 ', 2),
 ('11030 ', 2),
 ('1824 ', 2),
 ('20120 ', 2),
 ('20160 ', 2),
 ('23200 ', 2),
 ('23420 ', 2),
 ('24440 ', 2),
 ('25400 ', 2),
 ('26702 ', 2),
 ('27520 ', 2),
 ('2852 ', 2),
 ('28930 ', 2),
 ('28960 ', 2),
 ('29202 ', 2),
 ('32200 ', 2),
 ('32910 ', 2),
 ('38310 ', 2),
 ('4534 ', 2),
 ('4542 ', 2),
 ('46230 ', 2),
 ('47591 ', 2),
 ('49311 ', 2),
 ('50400 ', 2),
 ('5142 ', 2),
 ('5147 ', 2),
 ('5184 ', 2),
 ('5510 ', 2),
 ('5552 ', 2),
 ('6024 ', 2),
 ('6340 ', 2),
 ('6512 ', 2),
 ('6523 ', 2),
 ('6712 ', 2),
 ('7221 ', 2),
 ('7222 ', 2),
 ('7440 ', 2),
 ('77352 ', 2),
 ('8010 ', 2),
 ('84300 ', 2),
 ('9220 ', 2),
 ('9234 ', 2),
 ('9272 ', 2),
 ('9999 ', 2),
 ('01120 ', 3),
 ('01450 ', 3),
 ('01640 ', 3),
 ('10120 ', 3),
 ('10611 ', 3),
 ('10620 ', 3),
 ('10810 ', 3),
 ('10822 ', 3),
 ('13100 ', 3),
 ('13922 ', 3),
 ('16240 ', 3),
 ('17219 ', 3),
 ('18110 ', 3),
 ('20110 ', 3),
 ('20130 ', 3),
 ('20302 ', 3),
 ('22110 ', 3),
 ('2213 ', 3),
 ('23610 ', 3),
 ('25610 ', 3),
 ('25720 ', 3),
 ('26513 ', 3),
 ('28131 ', 3),
 ('28140 ', 3),
 ('28150 ', 3),
 ('28220 ', 3),
 ('30400 ', 3),
 ('38220 ', 3),
 ('43130 ', 3),
 ('4525 ', 3),
 ('4531 ', 3),
 ('46440 ', 3),
 ('49500 ', 3),
 ('5010 ', 3),
 ('5020 ', 3),
 ('51220 ', 3),
 ('5248 ', 3),
 ('65202 ', 3),
 ('7020 ', 3),
 ('7250 ', 3),
 ('7460 ', 3),
 ('77120 ', 3),
 ('77310 ', 3),
 ('84210 ', 3),
 ('91040 ', 3),
 ('9262 ', 3),
 ('9302 ', 3),
 ('93210 ', 3),
 ('01160 ', 4),
 ('01290 ', 4),
 ('02200 ', 4),
 ('03120 ', 4),
 ('03220 ', 4),
 ('08910 ', 4),
 ('10520 ', 4),
 ('10910 ', 4),
 ('11040 ', 4),
 ('13200 ', 4),
 ('19209 ', 4),
 ('20150 ', 4),
 ('22220 ', 4),
 ('23120 ', 4),
 ('23190 ', 4),
 ('23440 ', 4),
 ('24450 ', 4),
 ('25120 ', 4),
 ('25730 ', 4),
 ('26701 ', 4),
 ('27200 ', 4),
 ('28120 ', 4),
 ('30110 ', 4),
 ('30990 ', 4),
 ('31030 ', 4),
 ('32130 ', 4),
 ('32401 ', 4),
 ('35220 ', 4),
 ('3663 ', 4),
 ('46240 ', 4),
 ('47230 ', 4),
 ('52102 ', 4),
 ('52212 ', 4),
 ('52242 ', 4),
 ('5244 ', 4),
 ('6522 ', 4),
 ('7411 ', 4),
 ('7450 ', 4),
 ('9211 ', 4),
 ('01250 ', 5),
 ('03110 ', 5),
 ('03210 ', 5),
 ('10110 ', 5),
 ('13910 ', 5),
 ('16100 ', 5),
 ('17211 ', 5),
 ('19201 ', 5),
 ('23990 ', 5),
 ('24200 ', 5),
 ('26600 ', 5),
 ('28110 ', 5),
 ('28302 ', 5),
 ('28490 ', 5),
 ('30120 ', 5),
 ('33160 ', 5),
 ('42130 ', 5),
 ('47300 ', 5),
 ('47741 ', 5),
 ('5263 ', 5),
 ('5530 ', 5),
 ('7499 ', 5),
 ('77341 ', 5),
 ('82912 ', 5),
 ('84230 ', 5),
 ('91030 ', 5),
 ('01420 ', 6),
 ('01629 ', 6),
 ('11020 ', 6),
 ('17290 ', 6),
 ('20301 ', 6),
 ('20412 ', 6),
 ('27320 ', 6),
 ('27510 ', 6),
 ('28940 ', 6),
 ('29310 ', 6),
 ('30300 ', 6),
 ('30920 ', 6),
 ('33110 ', 6),
 ('5190 ', 6),
 ('52241 ', 6),
 ('55202 ', 6),
 ('6420 ', 6),
 ('7260 ', 6),
 ('84250 ', 6),
 ('01700 ', 7),
 ('05102 ', 7),
 ('10130 ', 7),
 ('13950 ', 7),
 ('23410 ', 7),
 ('27120 ', 7),
 ('28290 ', 7),
 ('29201 ', 7),
 ('42210 ', 7),
 ('52101 ', 7),
 ('55300 ', 7),
 ('5540 ', 7),
 ('77342 ', 7),
 ('81291 ', 7),
 ('84220 ', 7),
 ('91011 ', 7),
 ('91012 ', 7),
 ('91020 ', 7),
 ('07100 ', 8),
 ('10519 ', 8),
 ('10720 ', 8),
 ('13960 ', 8),
 ('14120 ', 8),
 ('20140 ', 8),
 ('20530 ', 8),
 ('27110 ', 8),
 ('30200 ', 8),
 ('4545 ', 8),
 ('46350 ', 8),
 ('46620 ', 8),
 ('55201 ', 8),
 ('59140 ', 8),
 ('77330 ', 8),
 ('93191 ', 8),
 ('95230 ', 8),
 ('12000 ', 9),
 ('24100 ', 9),
 ('26120 ', 9),
 ('26309 ', 9),
 ('26512 ', 9),
 ('46431 ', 9),
 ('46630 ', 9),
 ('46660 ', 9),
 ('52213 ', 9),
 ('64192 ', 9),
 ('7415 ', 9),
 ('81221 ', 9),
 ('9305 ', 9),
 ('95240 ', 9),
 ('02400 ', 10),
 ('10831 ', 10),
 ('10860 ', 10),
 ('14142 ', 10),
 ('18121 ', 10),
 ('26520 ', 10),
 ('47520 ', 10),
 ('64305 ', 10),
 ('77299 ', 10),
 ('95120 ', 10),
 ('01300 ', 11),
 ('01490 ', 11),
 ('13923 ', 11),
 ('17220 ', 11),
 ('17230 ', 11),
 ('23700 ', 11),
 ('64110 ', 11),
 ('74203 ', 11),
 ('84130 ', 11),
 ('94200 ', 11),
 ('95290 ', 11),
 ('10410 ', 12),
 ('22190 ', 12),
 ('24410 ', 12),
 ('35230 ', 12),
 ('42910 ', 12),
 ('46770 ', 12),
 ('47220 ', 12),
 ('68202 ', 12),
 ('01630 ', 13),
 ('10612 ', 13),
 ('25620 ', 13),
 ('35300 ', 13),
 ('46650 ', 13),
 ('64302 ', 13),
 ('98200 ', 13),
 ('01130 ', 14),
 ('10390 ', 14),
 ('15200 ', 14),
 ('32300 ', 14),
 ('50100 ', 14),
 ('52243 ', 14),
 ('77210 ', 14),
 ('94920 ', 14),
 ('01610 ', 15),
 ('06200 ', 15),
 ('11050 ', 15),
 ('13921 ', 15),
 ('16290 ', 15),
 ('21200 ', 15),
 ('26511 ', 15),
 ('28990 ', 15),
 ('29320 ', 15),
 ('33130 ', 15),
 ('45400 ', 15),
 ('77320 ', 15),
 ('82911 ', 15),
 ('01110 ', 16),
 ('02100 ', 16),
 ('10920 ', 16),
 ('33150 ', 16),
 ('35120 ', 16),
 ('46210 ', 16),
 ('46330 ', 16),
 ('47210 ', 16),
 ('64992 ', 16),
 ('7011 ', 16),
 ('01280 ', 17),
 ('31020 ', 17),
 ('37000 ', 17),
 ('47799 ', 17),
 ('51101 ', 17),
 ('95210 ', 17),
 ('98100 ', 17),
 ('01430 ', 18),
 ('10832 ', 18),
 ('46220 ', 18),
 ('46740 ', 18),
 ('47260 ', 18),
 ('47430 ', 18),
 ('47620 ', 18),
 ('47782 ', 18),
 ('52220 ', 18),
 ('59133 ', 18),
 ('61300 ', 18),
 ('77291 ', 18),
 ('79901 ', 18),
 ('46610 ', 19),
 ('47722 ', 19),
 ('49200 ', 19),
 ('82920 ', 19),
 ('10850 ', 20),
 ('18202 ', 20),
 ('18203 ', 20),
 ('29100 ', 20),
 ('46360 ', 20),
 ('47810 ', 20),
 ('7414 ', 20),
 ('26200 ', 21),
 ('27400 ', 21),
 ('33170 ', 21),
 ('46730 ', 21),
 ('64201 ', 21),
 ('81229 ', 21),
 ('85530 ', 21),
 ('14110 ', 22),
 ('25990 ', 22),
 ('26110 ', 22),
 ('47530 ', 22),
 ('47791 ', 22),
 ('49100 ', 22),
 ('84240 ', 22),
 ('13300 ', 23),
 ('20590 ', 23),
 ('43110 ', 23),
 ('46711 ', 23),
 ('47421 ', 23),
 ('52230 ', 23),
 ('58120 ', 23),
 ('58141 ', 23),
 ('95250 ', 23),
 ('13990 ', 24),
 ('33200 ', 24),
 ('36000 ', 24),
 ('43991 ', 24),
 ('46439 ', 24),
 ('46719 ', 24),
 ('46750 ', 24),
 ('47630 ', 24),
 ('51102 ', 24),
 ('77351 ', 24),
 ('96030 ', 24),
 ('33120 ', 25),
 ('75000 ', 25),
 ('97000 ', 25),
 ('82190 ', 26),
 ('27900 ', 27),
 ('33140 ', 27),
 ('35130 ', 27),
 ('60100 ', 27),
 ('78101 ', 27),
 ('10821 ', 28),
 ('11010 ', 28),
 ('15120 ', 28),
 ('4521 ', 28),
 ('47610 ', 28),
 ('46320 ', 29),
 ('47429 ', 29),
 ('47540 ', 29),
 ('56301 ', 29),
 ('58130 ', 29),
 ('10320 ', 30),
 ('10840 ', 30),
 ('18201 ', 30),
 ('21100 ', 30),
 ('38320 ', 30),
 ('47650 ', 30),
 ('66210 ', 30),
 ('85421 ', 30),
 ('47730 ', 31),
 ('96010 ', 31),
 ('38210 ', 32),
 ('51210 ', 32),
 ('69101 ', 32),
 ('84110 ', 32),
 ('84120 ', 32),
 ('11070 ', 33),
 ('22290 ', 33),
 ('25110 ', 33),
 ('33190 ', 33),
 ('42110 ', 33),
 ('43342 ', 33),
 ('53100 ', 33),
 ('63910 ', 33),
 ('20411 ', 34),
 ('59132 ', 34),
 ('65300 ', 34),
 ('16230 ', 35),
 ('43120 ', 35),
 ('49319 ', 35),
 ('80300 ', 35),
 ('95220 ', 35),
 ('46380 ', 36),
 ('77390 ', 36),
 ('07290 ', 37),
 ('32409 ', 37),
 ('47250 ', 37),
 ('77400 ', 37),
 ('95110 ', 37),
 ('46110 ', 38),
 ('47240 ', 38),
 ('7412 ', 38),
 ('85410 ', 38),
 ('31010 ', 39),
 ('43310 ', 39),
 ('46130 ', 39),
 ('65110 ', 39),
 ('01500 ', 40),
 ('31090 ', 40),
 ('46720 ', 40),
 ('47721 ', 40),
 ('08990 ', 41),
 ('52103 ', 41),
 ('74201 ', 41),
 ('47510 ', 42),
 ('64204 ', 42),
 ('85422 ', 42),
 ('20420 ', 43),
 ('47749 ', 43),
 ('46341 ', 44),
 ('14132 ', 45),
 ('26400 ', 45),
 ('35210 ', 45),
 ('46760 ', 45),
 ('88910 ', 45),
 ('09900 ', 46),
 ('47820 ', 46),
 ('53202 ', 46),
 ('64203 ', 46),
 ('72200 ', 46),
 ('93110 ', 46),
 ('53201 ', 47),
 ('94910 ', 47),
 ('10710 ', 48),
 ('39000 ', 48),
 ('42120 ', 48),
 ('46690 ', 48),
 ('52219 ', 48),
 ('82200 ', 48),
 ('71112 ', 49),
 ('81300 ', 49),
 ('64921 ', 50),
 ('88100 ', 50),
 ('45190 ', 51),
 ('82301 ', 51),
 ('86102 ', 51),
 ('18130 ', 52),
 ('32500 ', 52),
 ('59131 ', 52),
 ('46470 ', 53),
 ('47781 ', 54),
 ('14131 ', 55),
 ('90040 ', 55),
 ('38110 ', 58),
 ('43330 ', 58),
 ('85310 ', 58),
 ('49420 ', 59),
 ('42220 ', 60),
 ('45320 ', 60),
 ('46370 ', 60),
 ('64202 ', 60),
 ('43320 ', 61),
 ('66290 ', 61),
 ('45310 ', 62),
 ('74300 ', 62),
 ('92000 ', 62),
 ('46310 ', 64),
 ('47760 ', 64),
 ('7487 ', 64),
 ('87100 ', 64),
 ('43910 ', 66),
 ('47410 ', 66),
 ('74202 ', 66),
 ('46120 ', 67),
 ('46410 ', 67),
 ('46140 ', 68),
 ('87200 ', 68),
 ('50200 ', 69),
 ('74902 ', 69),
 ('81222 ', 69),
 ('55209 ', 70),
 ('64910 ', 70),
 ('81299 ', 70),
 ('46390 ', 71),
 ('85100 ', 71),
 ('93120 ', 72),
 ('85200 ', 73),
 ('09100 ', 75),
 ('43341 ', 75),
 ('80200 ', 75),
 ('60200 ', 76),
 ('64191 ', 76),
 ('71200 ', 76),
 ('85320 ', 77),
 ('64929 ', 78),
 ('74209 ', 78),
 ('81100 ', 80),
 ('82302 ', 80),
 ('69203 ', 81),
 ('45111 ', 83),
 ('47290 ', 83),
 ('47890 ', 83),
 ('49390 ', 83),
 ('86230 ', 84),
 ('35140 ', 85),
 ('06100 ', 86),
 ('49320 ', 86),
 ('65120 ', 86),
 ('85510 ', 87),
 ('46499 ', 88),
 ('74901 ', 89),
 ('62030 ', 90),
 ('87900 ', 90),
 ('93130 ', 91),
 ('47599 ', 92),
 ('77110 ', 93),
 ('79909 ', 93),
 ('46460 ', 95),
 ('66110 ', 95),
 ('59120 ', 97),
 ('73200 ', 97),
 ('10890 ', 99),
 ('46520 ', 100),
 ('46150 ', 104),
 ('47640 ', 104),
 ('58142 ', 105),
 ('87300 ', 106),
 ('42990 ', 107),
 ('61200 ', 107),
 ('47789 ', 109),
 ('64306 ', 109),
 ('66220 ', 116),
 ('71121 ', 116),
 ('46342 ', 117),
 ('47110 ', 117),
 ('72110 ', 117),
 ('64922 ', 118),
 ('18129 ', 119),
 ('94120 ', 123),
 ('66120 ', 127),
 ('72190 ', 127),
 ('79120 ', 128),
 ('46170 ', 129),
 ('61100 ', 132),
 ('46480 ', 133),
 ('46510 ', 136),
 ('14190 ', 139),
 ('58210 ', 140),
 ('64301 ', 144),
 ('86101 ', 144),
 ('85520 ', 145),
 ('86210 ', 145),
 ('94110 ', 145),
 ('68201 ', 147),
 ('32120 ', 149),
 ('96040 ', 149),
 ('64991 ', 155),
 ('45200 ', 157),
 ('81210 ', 161),
 ('55900 ', 162),
 ('69202 ', 163),
 ('64304 ', 168),
 ('88990 ', 179),
 ('32990 ', 186),
 ('46450 ', 190),
 ('43290 ', 192),
 ('86220 ', 193),
 ('43220 ', 196),
 ('47750 ', 197),
 ('94990 ', 201),
 ('52290 ', 205),
 ('56102 ', 214),
 ('43390 ', 220),
 ('99000 ', 221),
 ('47770 ', 227),
 ('46160 ', 233),
 ('69102 ', 239),
 ('93199 ', 243),
 ('73120 ', 247),
 ('64303 ', 249),
 ('78300 ', 250),
 ('82110 ', 251),
 ('69109 ', 254),
 ('58110 ', 255),
 ('46180 ', 256),
 ('56210 ', 256),
 ('71129 ', 262),
 ('43210 ', 263),
 ('80100 ', 263),
 ('66190 ', 265),
 ('45112 ', 266),
 ('90020 ', 269),
 ('93290 ', 269),
 ('62011 ', 280),
 ('56302 ', 286),
 ('55100 ', 297),
 ('79110 ', 301),
 ('46420 ', 308),
 ('56103 ', 308),
 ('59113 ', 325),
 ('78200 ', 329),
 ('41201 ', 331),
 ('61900 ', 339),
 ('49410 ', 343),
 ('71122 ', 351),
 ('59200 ', 352),
 ('90010 ', 361),
 ('56290 ', 366),
 ('43999 ', 379),
 ('71111 ', 402),
 ('66300 ', 416),
 ('59112 ', 422),
 ('70210 ', 422),
 ('63110 ', 423),
 ('58190 ', 426),
 ('96020 ', 444),
 ('85600 ', 458),
 ('98000 ', 461),
 ('41202 ', 463),
 ('70221 ', 468),
 ('47190 ', 477),
 ('47710 ', 478),
 ('63120 ', 492),
 ('59111 ', 494),
 ('68310 ', 496),
 ('58290 ', 521),
 ('56101 ', 545),
 ('90030 ', 559),
 ('46190 ', 573),
 ('69201 ', 587),
 ('74100 ', 615),
 ('46900 ', 621),
 ('85590 ', 640),
 ('64205 ', 657),
 ('63990 ', 658),
 ('47990 ', 713),
 ('68320 ', 786),
 ('35110 ', 841),
 ('78109 ', 952),
 ('70100 ', 982),
 ('86900 ', 1012),
 ('73110 ', 1105),
 ('74909 ', 1361),
 ('74990 ', 1368),
 ('64999 ', 1719),
 ('68209 ', 1745),
 ('41100 ', 1954),
 ('62090 ', 2020),
 ('64209 ', 2086),
 ('68100 ', 2263),
 ('99999 ', 2454),
 ('62012 ', 2580),
 ('47910 ', 3258),
 ('None Supplied', 3316),
 ('62020 ', 3448),
 ('96090 ', 3526),
 ('70229 ', 4573),
 ('82990 ', 7229)]

# Create new df specific to sectors

In [15]:
# find names for certain sector values

# create new data frame for sector values
columns = [
    'IncorporationDate',
    'year',
    'month',
    'CompanyName',
    'CompanyNumber',
    'CompanyStatus',
    'sector_code_1',
    'sector_name_1',
]

# create new df with columns
sector_data = cleaned_data[columns]

# sort by sector code
sector_data.sort_values(by=['sector_code_1', 'sector_name_1'],
                        ascending=True).head(20)

,IncorporationDate,year,month,CompanyName,CompanyNumber,CompanyStatus,sector_code_1,sector_name_1
71862,1998-04-11,1998,4,RATTLEROW FARMS LIMITED,03661333,Active,01110,"Growing of cereals (except rice), leguminous ..."
72958,2002-08-11,2002,8,RENEWABLE FUELS LIMITED,04585729,Active,01110,"Growing of cereals (except rice), leguminous ..."
94057,2009-04-24,2009,4,WARRENS EMERALD BIOGAS LTD,06887312,Active,01110,"Growing of cereals (except rice), leguminous ..."
93357,2010-04-02,2010,4,VITAL FARMING LIMITED,07145886,Active,01110,"Growing of cereals (except rice), leguminous ..."
73072,2018-03-15,2018,3,RESDEFA LTD.,11257910,Active,01110,"Growing of cereals (except rice), leguminous ..."
75004,2018-05-15,2018,5,RUSH CAPITAL LTD,11361777,Active,01110,"Growing of cereals (except rice), leguminous ..."
69461,2019-01-30,2019,1,PRIMETECH INVESTMENTS LTD,11798053,Active - Proposal to Strike off,01110,"Growing of cereals (except rice), leguminous ..."
34239,2019-03-14,2019,3,GARRY CAPITAL UK LTD,11882130,Active - Proposal to Strike off,01110,"Growing of cereals (except rice), leguminous ..."
18901,2019-04-11,2019,4,COALITION EMPIRE CORPORATE PRIVATE LIMITED,12297339,Active,01110,"Growing of cereals (except rice), leguminous ..."
33974,2019-05-16,2019,5,GADDOUH LTD,11999287,Active,01110,"Growing of cereals (except rice), leguminous ..."
36928,2019-08-30,2019,8,GREEN HAND LONDON LTD,12180920,Active,01110,"Growing of cereals (except rice), leguminous ..."
57184,2020-01-10,2020,1,MHR SEEDS LTD,12917581,Active,01110,"Growing of cereals (except rice), leguminous ..."
76050,2020-02-28,2020,2,SARO TRADING LTD,12489162,Active,01110,"Growing of cereals (except rice), leguminous ..."
42534,2020-04-06,2020,4,INCE GLOBAL TRADING LTD,12645496,Active,01110,"Growing of cereals (except rice), leguminous ..."
3266,2020-07-08,2020,7,AGRIC LIMITED,12798631,Active,01110,"Growing of cereals (except rice), leguminous ..."
90032,2020-08-19,2020,8,TROY FOOD AND COMMERCE LTD,12825185,Active,01110,"Growing of cereals (except rice), leguminous ..."
10097,2018-02-26,2018,2,BEFORA EVENT LTD,11223784,Active,01120,Growing of rice
3679,2020-07-30,2020,7,AKKGCONSULTANCYLTD.COM LIMITED,12781508,Active,01120,Growing of rice
31019,2020-09-17,2020,9,FEED THE WORLD GROUP LTD,12885285,Active,01120,Growing of rice
73452,2010-01-16,2010,1,RGJ POWER LTD,07127311,Active,01130,"Growing of vegetables and melons, roots and t..."

In [16]:
# save data as csv
save_path = os.path.join(base_path, 'datasets', 'final_cleaned_data.csv')
sector_data.to_csv(save_path, index=False)